import {  createSlice } from '@reduxjs/toolkit';
const initialState = {
  sendMessageIsOpen: false,
};



export const mailSlice = createSlice({
  name: 'mail',
  initialState,
  reducers: {
    OpenSendMessage: (state) => {
      
      state.sendMessageIsOpen = true;
    },
    closeSendMessage: (state) => {
      state.sendMessageIsOpen = false;
    },
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
});

export const { OpenSendMessage, closeSendMessage } = mailSlice.actions;

// The function below is called a selector and allows us to select a value from
// the state. Selectors can also be defined inline where they're used instead of
// in the slice file. For example: `useSelector((state: RootState) => state.counter.value)`
export const selectsendMessageIsOpen = (state) => state.mail.sendMessageIsOpen;

// We can also write thunks by hand, which may contain both sync and async logic.
// Here's an example of conditionally dispatching actions based on current state.


export default mailSlice.reducer;
